highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 7
paginate_path: "page:num"
layout: post
permalink: /:categories/:title
excerpt_separator: "[-----]"

url: https://junyeong-je.github.io # Required: replace this with your domain
# Google Search Console에서 사용하는 sitemap.xml 생성시
# 이 url key값이 존재하지 않으면 sitemap.xml이
# 정상적으로 생성되지 않는다.
# 또한 disqus(댓글시스템)를 이용하기 위해서도 필요.
# 자신의 github page url을 입력
# ( https://your_github_id.github.io 형식 )

baseurl: /
name: techlog # Required: will be displayed on every page's header
title: Techlog # Required: site's default title
shout: # Required: **TWO** lines, will be displayed on page's header.
  - Public Cloud
  - System Technic
description: "IT tech, personal thoughts and other things..." # Required

disqus:
  comments: true # Global toggle on/off disqus comment
  shortname: junyeong-techlog # Required if you use disqus. Repalce with your disqus shortname here

google_analytics:
  id: "UA-168126711-1" # Required if you use google analytics. Replace with your tracking id here

collections: # Define post series here
  book_review:
    output: true
  tmp:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"